GIS_DATABASE_NAME = "gis"

GEOLOCATION_TABLE_NAME = "geolocation" #tbl1
GEOLOCATION_TABLE_ID = "id"
GEOLOCATION_TABLE_X = "x"
GEOLOCATION_TABLE_Y = "y"
GEOLOCATION_TABLE_IMPORTANCE = "importance"

TOPOLOGY_TABLE_NAME = "topology" #tbl2
TOPOLOGY_TABLE_LOC1_ID = "loc1_id"
TOPOLOGY_TABLE_LOC2_ID = "loc2_id"
TOPOLOGY_TABLE_DISTANCE = "distance"

# 创建database中的table